services:
  # auth-server:
  #   build: .
  #   container_name: central-auth-server
  #   ports:
  #     - "8081:8081"
  #   depends_on:
  #     - redis
  #   environment:
  #     - REDIS_ADDR=redis:6379
  #   restart: always

  redis:
    image: redis:7-alpine
    container_name: central-auth-redis
    ports:
      - "6379:6379"
    restart: always
